### ISSUE TITLE
Mailing Lists for each IPFS Working Group

### ISSUE THREAD

**Issue by daviddias** [ipfs/project#10]
Mailing lists are a great way to have a conversation with multiple stakeholders and at the same time, preserve the conversation for future selfs and future contributors. Github issues are similar, however, one can't really make the opt-in/opt-out decision on Github (new repos get created, once tagged you get notifications forever, etc).

Given this, would Working Groups like to have a mlist for their team? @ipfs/working-group-captains, if yes, comment on this thread.

**Comment by vmx** [comment]
Will those mailing list public and open for everyone (also the archives)?

**Comment by diasdavid** [comment]
@vmx up to the Working Group to decide. I recommend to default open

**Comment by mikeal** [comment]
So, I'm -1 on creating more public mailing lists, but I'm +1 on each WG having a point of contact.

I'd be open to either a GitHub repo for discussion per WG **or** trying to accomplish this using https://discuss.ipfs.io/

> Github issues are similar, however, one can't really make the opt-in/opt-out decision on Github (new repos get created, once tagged you get notifications forever, etc).

If you are on the org you can opt out of repos, if you are @ msg'd you can opt out of that individual issue :)

Mailing Lists, by comparison, are all or nothing. The issue you're describing is much worse with mailing lists, the only reason it seems like less is because it's less accessible and therefor has less traffic :)

> Need: A way to share sensitive conversations within a working group

Can we clarify some of the use cases here outside of secuirty (which we already have a separate process for).

> Need: A way to permission-share sensitive documents within the IPFS project

Doesn't Google Apps have group permissions for this? We tend to use the protocol.ai permission system but we could use the ipfs.io Google App permission system instead.

> Need: A way for new core contributors to easily gain access to relevant documents / announcements when joining the project

This is certainly an issue, but I feel like this is a discovery and context problem much more than a transparency problem.

**Comment by momack2** [comment]
> > Need: A way to share sensitive conversations within a working group
> 
> Can we clarify some of the use cases here outside of secuirty (which we already have a separate process for).

The examples I included were quarterly retrospectives (which include self reflections that might be sensitive) and team meetup logistics/coordination - both of which we currently use direct emails to coordinate (and try not to forget anyone).

> > Need: A way to permission-share sensitive documents within the IPFS project
> 
> Doesn't Google Apps have group permissions for this? We tend to use the protocol.ai permission system but we could use the ipfs.io Google App permission system instead.

You need to have a google group or an organization where everyone has an email to do group permissions in Google Apps. Therefore we'd either need to create and keep updated wg google groups (proposal 2) or create all contributors ipfs.io emails to access permissioned docs (proposal 4).

**Comment by mikeal** [comment]
> You need to have a google group or an organization where everyone has an email to do group permissions in Google Apps. Therefore we'd either need to create and keep updated wg google groups (proposal 2) or create all contributors ipfs.io emails to access permissioned docs (proposal 4).

Technical question: if you add emails that are not in the domain for the app to a group are they included in the permission scheme when you add them to documents? In Google Apps you pay per seat but that only applies to people you add to the org and get an in-domain email address.

BTW, I know that Google Apps makes a "Group" and a "Mailing List" effectively the same thing. I'm more concerned with how we treat them, if it's just a group email alias I have no objections, if we start treating it like a long term mailing list with lots of discussion that's when I grow concerned. The difference here is probably whether or not we open it up publicly.

**Comment by momack2** [comment]
> Technical question: if you add emails that are not in the domain for the app to a group are they included in the permission scheme when you add them to documents?

Yes - if we create google groups with emails from a variety of organizations to properly reference working group contributors from many orgs, they will still be permissioned on docs accordingly.

I agree with the motivation - we want all conversation to be public that doesn't explicitly need access controls. Is a policy around that sufficient, or would you want to add anything to the proposal(s) specifically to enforce that? I think there are cases where the communication needed would be an email (ex about coordinating wg meetup logistics), so turning off list posting entirely seems counter productive.

**Comment by mikeal** [comment]
> I agree with the motivation - we want all conversation to be public that doesn't explicitly need access controls. Is a policy around that sufficient, or would you want to add anything to the proposal(s) specifically to enforce that? I think there are cases where the communication needed would be an email (ex about coordinating wg meetup logistics), so turning off list posting entirely seems counter productive.

I'm not worried about people not on the list posting and interacting with the list when they are explicitly looped in via email.

I was mainly concerned that we were creating another fully open forum to manage. What you're proposing a specific tool for side channel conversations we do not want to make public, in which case this sounds perfect. And, as a bonus, we can include people out of the org in the WG list, so I think I'm totally on board.

**Comment by momack2** [comment]
@daviddias @vmx - sounds like Mikeal and I are onboard with proposal 2.1 (where mlist messages are only visible to group members). Any concerns? If not I'll take a pass at creating mlists for each wg (with captains as owners) in ipfs.io and add documentation to our [team coordination toolkit](https://github.com/ipfs/team-mgmt/blob/master/TEAM_COORDINATION_TOOLKIT.md) re communication channels and membership.

**Comment by vmx** [comment]
> sounds like Mikeal and I are onboard with proposal 2.1

@momack2 I'm fine with that, I saw my comment more as input rather than a blocker.

**Comment by momack2** [comment]
### Decision from IPFS Project Weekly
We are planning to prototype **proposal 2** for the next ~month to evaluate the value of this solution and any pain points uncovered that we want to iterate on. We will reconvene EOJan to decide whether to amend the proposal or finalize the implementation. If finalized, we'll work to implement the "history deletion" element  of **proposal 2.1** on top of the current setup, and any additional systematization to keep these lists accurate and useful.

### Status Update
I have created a private working group google group for each of the IPFS working groups, and made the WG captain the owner and added all known WG members. Captains should feel free to update this group according to their understanding of working group members, and approve/deny any membership requests accordingly. There is also an "IPFS Core Contributors" group (ipfs-core-contributors@ipfs.io) that contains references to all working group lists and can be used for private/sensitive org-wide permissioning/conversation. @daviddias can add any additional members he considers part of the IPFS org.

_All lists are in the form of `[working group abbreviation]-wg@ipfs.io` (see the [2019 OKR sheet](https://docs.google.com/spreadsheets/d/1BtOfd7s9oYO5iKsIorCpsm4QuQoIsoZzSz7GItE-9ys/edit#gid=1681757723) for canonical abbreviations)_
![screen shot 2018-12-13 at 4 33 09 pm](https://user-images.githubusercontent.com/618519/49975974-0cccef80-fef5-11e8-9f4c-e7d9ea34cce4.png)

**Comment by daviddias** [comment]
@momack2 stellar work!! ✨✨✨

@ipfs/working-group-captains, can we count on you to:
- List the mlist in your entry-point repo
- Add your Working Group contributors to the mlist

**Comment by daviddias** [comment]
List of mlists for easy access:

- project-wg@ipfs.io
- dds-wg@ipfs.io
- ddc-wg@ipfs.io
- community-wg@ipfs.io
- cluster-wg@ipfs.io
- gui-wg@ipfs.io
- wb-wg@ipfs.io
- go-ipfs-wg@ipfs.io
- js-ipfs-wg@ipfs.io
- ipfs-core-contributors@ipfs.io
- locol-wg@ipfs.io
- infra-wg@ipfs.io

**Comment by daviddias** [comment]
I've created a PR to add the mlits to the Team Structures doc https://github.com/ipfs/team-mgmt/pull/807

**Comment by momack2** [comment]
> @daviddias not sure if I got this right, but AFAIK only members can post to wb-wg list right now:

I can (and will!) change this! For sharing docs and stuff, it's actually really useful if non-wg members can post to these lists with private collab docs and such - thanks for catching this. 

However, I don't think we want to route initial engagement to these lists - we want to keep doing our work in the open on github whenever possible! Putting this on our page seems like it's asking for us to either get spammed, or for people to route comms there that should actually just be github issues...

**Comment by meiqimichelle** [comment]
It would be great to close out this issue, but looking back, I think there's a point of confusion:

- It seems like we converged on *not* publicizing these lists because we already have ways for the community to interact with the WGs, and we don't want to add yet another channel to maintain (and we want to keep most conversations in the open). 

- We merged a PR that makes those email addresses public as "email contact" on the Team Structure page.

Was that intentional, or a miscommunication? We may need to roll back that change.

Once that's resolved, I think we can consider this process improvement on a ship! Then @momack2 -- did you want to keep this open, or open a new repo for the review in January?

**Comment by momack2** [comment]
A side benefit that we didn't explicitly design for in that these lists are organically getting used for confidential information and private intros from the community directly to the working group participants. Right now I think that's just happening because we are using these lists ourselves to route that communication from other channels, but it could be that this fills a useful gap in our community we didn't know we had. I think I still lean toward not posting them as one of the core ways to reach out to a working group (aka reverting [the PR](https://github.com/ipfs/team-mgmt/commit/702f4a36975ef141506b99c53b198f0f2c07db01#diff-ca5fe70b286df6e5e4acb856de2d7c66)) since it's hard to stop them being misused when presented in that context - but I think we should recognize and enable these lists being used by the wider community to coordinate privately with a working group when needed.

**Comment by momack2** [comment]
Desired communication by priority:
1. working group members communicating privately _within_ the working group (scheduling meetups, retrospectives, sensitive discussion/updates)
2. permissioning documents for within-team viewability (for the same reasons as above)
3. community members engaging on a private topic with a working group or initiating a personal introduction

Non-desired communication (should come through github directly):
1. feature requests and bug reports
2. requests for status updates 
3. suggestions and design proposals/discussions

We can try having these mailing lists front-and-center for now and changing how we document them if we start getting a lot of non-desired comms, but it's harder to move people away from that channel once they start using it.

**Comment by daviddias** [comment]
> but I think we should recognize and enable these lists being used by the wider community to coordinate privately with a working group when needed.

> community members engaging on a private topic with a working group or initiating a personal introduction

This was what my expectation was and so, making them listed for people to reach out was a natural step of it.

**Comment by momack2** [comment]
I think folks are commenting on the way they are being portrayed - as a generic "email contact" that doesn't give a good sense of what sort of contact should go through the email list vs the github repo. That structure seems to lend itself to misuse.

**Comment by momack2** [comment]
I'm more comfortable with "Mailing list" or "Working Group mlist" or something like that. @meiqimichelle @lidel - do either of those seem better to you?

**Comment by daviddias** [comment]
@momack2 got it. My bad for initially naming it "Contact". I know understand the resistance and I agree. "Mailing list" is indeed more useful term. Thank you for catching that!

**Comment by momack2** [comment]
Cool - I'll make a PR adding those back in. I suggest **"Team Mailing List"** or **"Working Group Mailing List"** (maybe **"WG Mailing List"**?) over plain _"Mailing List"_ - since it's more clear that it's for core contributors within the working group, not a default place to send bugs/requests/feedback or a broadcast announce list for anyone interested in that working group's efforts. 

I'll go with the longer/clearer one in my PR but feel free to add comments!

**Comment by momack2** [comment]
We discussed this in our Project WG meeting this week and decided to solidify this prototype - where they are being used, these mailing lists are adding value without any obvious pain points to iterate on. We will check back in around EOQ2 to evaluate if/how to implement content expiry.
